CREATE DATABASE IF NOT EXISTS company_analysis_project;
USE company_analysis_project;

DROP TABLE IF EXISTS companies;

CREATE TABLE companies (
  id VARCHAR(20) PRIMARY KEY,
  source_row_number INT,
  entity_type VARCHAR(50),
  entity_id INT,
  parent_id VARCHAR(20),
  company_name VARCHAR(255),
  normalized_name VARCHAR(255),
  permalink VARCHAR(255),
  category_code VARCHAR(100),
  status VARCHAR(50),
  founded_at DATE,
  closed_at DATE,
  domain VARCHAR(255),
  homepage_url VARCHAR(500),
  twitter_username VARCHAR(255),
  logo_url VARCHAR(500),
  logo_width DECIMAL(10,2),
  logo_height DECIMAL(10,2),
  short_description VARCHAR(500),
  description VARCHAR(500),
  overview LONGTEXT,
  tag_list TEXT,
  country_code VARCHAR(10),
  state_code VARCHAR(50),
  city VARCHAR(100),
  region VARCHAR(100),
  first_investment_at DATE,
  last_investment_at DATE,
  investment_rounds INT,
  invested_companies INT,
  first_funding_at DATE,
  last_funding_at DATE,
  funding_rounds INT,
  funding_total_usd DECIMAL(18,2),
  first_milestone_at DATE,
  last_milestone_at DATE,
  milestones INT,
  relationships INT,
  created_by VARCHAR(100),
  created_at DATETIME,
  updated_at DATETIME,
  lat DECIMAL(12,8),
  lng DECIMAL(12,8),
  roi DECIMAL(10,2)
);

LOAD DATA LOCAL INFILE 'D:/Downloads/companies.csv/companies.csv'
INTO TABLE companies
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(
  id,
  @source_row_number,
  entity_type,
  @entity_id,
  parent_id,
  company_name,
  normalized_name,
  permalink,
  category_code,
  status,
  @founded_at,
  @closed_at,
  domain,
  homepage_url,
  twitter_username,
  logo_url,
  @logo_width,
  @logo_height,
  short_description,
  description,
  overview,
  tag_list,
  country_code,
  state_code,
  city,
  region,
  @first_investment_at,
  @last_investment_at,
  @investment_rounds,
  @invested_companies,
  @first_funding_at,
  @last_funding_at,
  @funding_rounds,
  @funding_total_usd,
  @first_milestone_at,
  @last_milestone_at,
  @milestones,
  @relationships,
  created_by,
  @created_at,
  @updated_at,
  @lat,
  @lng,
  @roi
)
SET
  source_row_number = NULLIF(@source_row_number, ''),
  entity_id = NULLIF(@entity_id, ''),
  founded_at = NULLIF(@founded_at, ''),
  closed_at = NULLIF(@closed_at, ''),
  logo_width = NULLIF(@logo_width, ''),
  logo_height = NULLIF(@logo_height, ''),
  first_investment_at = NULLIF(@first_investment_at, ''),
  last_investment_at = NULLIF(@last_investment_at, ''),
  investment_rounds = NULLIF(@investment_rounds, ''),
  invested_companies = NULLIF(@invested_companies, ''),
  first_funding_at = NULLIF(@first_funding_at, ''),
  last_funding_at = NULLIF(@last_funding_at, ''),
  funding_rounds = NULLIF(@funding_rounds, ''),
  funding_total_usd = NULLIF(@funding_total_usd, ''),
  first_milestone_at = NULLIF(@first_milestone_at, ''),
  last_milestone_at = NULLIF(@last_milestone_at, ''),
  milestones = NULLIF(@milestones, ''),
  relationships = NULLIF(@relationships, ''),
  created_at = NULLIF(@created_at, ''),
  updated_at = NULLIF(@updated_at, ''),
  lat = NULLIF(@lat, ''),
  lng = NULLIF(@lng, ''),
  roi = NULLIF(TRIM(BOTH '\r' FROM @roi), '');
